# Generated by Django 5.0.6 on 2026-05-10 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kod')),
                ('standard_weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona og'irligi (kg)")),
                ('weaving_price_uzs', models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name="To'qish narxi (so'm)")),
                ('weaving_price_usd', models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name="To'qish narxi (dollar)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Mahsulot rasmi')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ombordagi soni (dona)')),
                ('min_stock_threshold', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimal zaxira chegarasi')),
                ('default_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.thread', verbose_name='Standart ip')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Yangilangan vaqt')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona uchun kerak bo'lgan ip miqdori (kg)")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='products.product')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Ip turi')),
            ],
            options={
                'verbose_name': 'Mahsulot ip tarkibi',
                'verbose_name_plural': 'Mahsulot ip tarkiblari',
                'unique_together': {('product', 'thread')},
            },
        ),
    ]
