# Generated by Django 5.0.6 on 2026-05-02 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kod')),
                ('standard_weight', models.DecimalField(decimal_places=3, help_text='1 dona tayyor mahsulot qancha kg kelishi kerak', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona mahsulotning standart og'irligi (kg)")),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sotish narxi')),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ishlab chiqarish tannarxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('default_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.thread', verbose_name='Standart ip')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
    ]
