# Generated by Django 5.0.6 on 2026-05-03 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='production_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='decoration_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bezak narxi (1 dona uchun)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weaving_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'qish narxi (1 dona uchun)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona mahsulotning standart og'irligi (kg)"),
        ),
    ]
