# Generated by Django 5.0.6 on 2026-05-03 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_production_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='decoration_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona og'irligi (kg)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='weaving_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="1 dona to'qish narxi (so'm)"),
        ),
    ]
