# Generated by Django 5.0.6 on 2026-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_decoration_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weaving_price',
        ),
        migrations.AddField(
            model_name='product',
            name='weaving_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'qish narxi (dollar)"),
        ),
        migrations.AddField(
            model_name='product',
            name='weaving_price_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'qish narxi (so'm)"),
        ),
    ]
