# Generated by Django 5.0.6 on 2026-05-05 19:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_weaving_price_and_more'),
        ('threads', '0002_threadsupplierdebt_supplierpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona uchun kerak bo'lgan ip miqdori (kg)")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='products.product')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Ip turi')),
            ],
            options={
                'verbose_name': 'Mahsulot ip tarkibi',
                'verbose_name_plural': 'Mahsulot ip tarkiblari',
                'unique_together': {('product', 'thread')},
            },
        ),
    ]
