# Generated by Django 5.0.6 on 2026-05-02 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('total_thread_taken', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Jami olingan ip (kg)')),
                ('total_product_given', models.IntegerField(default=0, verbose_name='Jami topshirilgan yaroqli mahsulot (dona)')),
                ('total_product_weight_given', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name="Jami topshirilgan yaroqli mahsulot og'irligi (kg)")),
                ('total_defective_product_given', models.IntegerField(default=0, verbose_name='Jami topshirilgan yaroqsiz mahsulot (dona)')),
                ('total_defective_weight_given', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name="Jami topshirilgan yaroqsiz mahsulot og'irligi (kg)")),
                ('master', models.OneToOneField(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
            ],
            options={
                'verbose_name': 'Usta balansi',
                'verbose_name_plural': 'Ustalar balanslari',
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Berilgan ip miqdori (kg)')),
                ('debt_type', models.CharField(choices=[('product', 'Tayyor mahsulot soni')], default='product', max_length=10, verbose_name='Qarz turi')),
                ('expected_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kutilayotgan mahsulot soni (dona)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Yopilgan')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('expected_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Kutilayotgan mahsulot')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usta')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Ip')),
            ],
            options={
                'verbose_name': 'Ip berish',
                'verbose_name_plural': 'Ip berishlar',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('receipt_date', models.DateField(auto_now_add=True, verbose_name='Qabul qilingan sana')),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qabul qilingan miqdor (dona)')),
                ('quality_status', models.CharField(choices=[('good', 'Yaroqli'), ('defective', 'Yaroqsiz'), ('repairable', 'Qayta tiklanadigan')], default='good', max_length=20, verbose_name='Sifat holati')),
                ('defect_reason', models.CharField(blank=True, choices=[('sewing', 'Tikish xatosi'), ('fabric', 'Mato nuqsoni'), ('size', "O'lcham xatosi"), ('cutting', 'Kesish xatosi'), ('other', 'Boshqa sabab')], max_length=20, null=True, verbose_name='Brak sababi')),
                ('defect_description', models.TextField(blank=True, verbose_name='Brak tavsifi')),
                ('actual_weight_per_item', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona mahsulotning haqiqiy og'irligi (kg)")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('material_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.materialissue', verbose_name='Ip berish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan')),
            ],
            options={
                'verbose_name': 'Mahsulot qabul qilish',
                'verbose_name_plural': 'Mahsulot qabul qilishlar',
                'ordering': ['-receipt_date'],
            },
        ),
    ]
