# Generated by Django 5.0.6 on 2026-05-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbalance',
            name='returned_defective_quantity',
            field=models.IntegerField(default=0, verbose_name='Qaytarilgan brak mahsulot (dona)'),
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='returned_defective_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name="Qaytarilgan brak og'irligi (kg)"),
        ),
        migrations.AddField(
            model_name='productreceipt',
            name='is_returned_to_master',
            field=models.BooleanField(default=False, verbose_name='Ustaga qaytarilgan'),
        ),
        migrations.AddField(
            model_name='productreceipt',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Qaytargan'),
        ),
        migrations.AddField(
            model_name='productreceipt',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qaytarilgan sana'),
        ),
        migrations.AlterField(
            model_name='productreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan'),
        ),
    ]
