# Generated by Django 5.0.6 on 2026-05-03 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_masterbalance_returned_defective_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbalance',
            name='returned_defective_quantity',
        ),
        migrations.RemoveField(
            model_name='masterbalance',
            name='returned_defective_weight',
        ),
        migrations.RemoveField(
            model_name='productreceipt',
            name='is_returned_to_master',
        ),
        migrations.RemoveField(
            model_name='productreceipt',
            name='returned_by',
        ),
        migrations.RemoveField(
            model_name='productreceipt',
            name='returned_date',
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_decoration_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami bezak haqqi'),
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_weaving_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Jami to'qish haqqi"),
        ),
        migrations.AlterField(
            model_name='masterbalance',
            name='total_defective_weight_given',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name="Jami topshirilgan yaroqsiz og'irlik (kg)"),
        ),
        migrations.AlterField(
            model_name='masterbalance',
            name='total_product_given',
            field=models.IntegerField(default=0, verbose_name='Jami topshirilgan mahsulot (dona)'),
        ),
        migrations.AlterField(
            model_name='masterbalance',
            name='total_product_weight_given',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name="Jami topshirilgan og'irlik (kg)"),
        ),
        migrations.AlterField(
            model_name='productreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan'),
        ),
    ]
