# Generated by Django 5.0.6 on 2026-05-03 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_masterbalance_returned_defective_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbalance',
            name='total_decoration_payment',
        ),
        migrations.RemoveField(
            model_name='masterbalance',
            name='total_defective_product_given',
        ),
        migrations.RemoveField(
            model_name='masterbalance',
            name='total_defective_weight_given',
        ),
        migrations.RemoveField(
            model_name='masterbalance',
            name='total_product_weight_given',
        ),
        migrations.RemoveField(
            model_name='masterbalance',
            name='total_thread_taken',
        ),
        migrations.RemoveField(
            model_name='masterbalance',
            name='total_weaving_payment',
        ),
        migrations.RemoveField(
            model_name='materialissue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='materialissue',
            name='debt_type',
        ),
        migrations.RemoveField(
            model_name='productreceipt',
            name='defect_description',
        ),
        migrations.RemoveField(
            model_name='productreceipt',
            name='received_by',
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_payment_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Jami to'lanadigan (so'm)"),
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_payment_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan (so'm)"),
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_weight_given',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name="Jami og'irlik (kg)"),
        ),
        migrations.AlterField(
            model_name='masterbalance',
            name='total_product_given',
            field=models.IntegerField(default=0, verbose_name='Jami topshirilgan (dona)'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='expected_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kutilayotgan son (dona)'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Berilgan ip (kg)'),
        ),
        migrations.AlterField(
            model_name='productreceipt',
            name='actual_weight_per_item',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name="1 dona og'irligi (kg)"),
        ),
        migrations.AlterField(
            model_name='productreceipt',
            name='quality_status',
            field=models.CharField(choices=[('good', 'Yaroqli'), ('defective', 'Yaroqsiz'), ('repairable', 'Qayta tiklanadigan')], default='good', max_length=20, verbose_name='Sifat'),
        ),
        migrations.AlterField(
            model_name='productreceipt',
            name='quantity_received',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdor (dona)'),
        ),
        migrations.AlterField(
            model_name='productreceipt',
            name='receipt_date',
            field=models.DateField(auto_now_add=True, verbose_name='Sana'),
        ),
    ]
