# Generated by Django 5.0.6 on 2026-05-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_masterbalance_total_decoration_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbalance',
            name='total_thread_taken',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Jami olingan ip (kg)'),
        ),
    ]
