# Generated by Django 5.0.6 on 2026-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_masterbalance_total_thread_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreceipt',
            name='defect_description',
            field=models.TextField(blank=True, verbose_name='Brak tavsifi'),
        ),
    ]
