# Generated by Django 5.0.6 on 2026-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productreceipt_defect_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterbalance',
            old_name='total_payment_due',
            new_name='total_payment_due_uzs',
        ),
        migrations.RenameField(
            model_name='masterbalance',
            old_name='total_payment_paid',
            new_name='total_payment_paid_uzs',
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_payment_due_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Jami to'lanadigan (dollar)"),
        ),
        migrations.AddField(
            model_name='masterbalance',
            name='total_payment_paid_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan (dollar)"),
        ),
    ]
