# Generated by Django 5.0.6 on 2026-05-05 19:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_materialissue_options_and_more'),
        ('products', '0005_productthread'),
        ('threads', '0002_threadsupplierdebt_supplierpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialissue',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Ip berish', 'verbose_name_plural': 'Ip berishlar'},
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='expected_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Kutilayotgan mahsulot'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='expected_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kutilayotgan son (dona)'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Yopilgan'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='issue_date',
            field=models.DateField(auto_now_add=True, verbose_name='Berilgan sana'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='master',
            field=models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usta'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Berilgan ip (kg)'),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threads.thread', verbose_name='Ip'),
        ),
    ]
