# Generated by Django 5.0.6 on 2026-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('uzs', "So'm"), ('usd', 'Dollar')], default='uzs', max_length=3, verbose_name='Afzal valyuta'),
        ),
    ]
