# Generated by Django 5.0.6 on 2026-05-02 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Ip nomi')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Rangi')),
                ('article', models.CharField(blank=True, max_length=50, verbose_name='Artikul')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name="O'lchov birligi")),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi (1 kg)')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Joriy qoldiq')),
                ('min_stock_threshold', models.DecimalField(decimal_places=3, default=10, max_digits=12, verbose_name='Minimal qoldiq chegarasi')),
            ],
            options={
                'verbose_name': 'Ip',
                'verbose_name_plural': 'Iplar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThreadTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Miqdor')),
                ('transaction_type', models.CharField(choices=[('incoming', 'Kirim'), ('outgoing', 'Chiqim'), ('return', 'Qaytarilgan'), ('write_off', 'Hisobdan chiqarish')], max_length=20, verbose_name='Harakat turi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('related_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tegishli usta')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='threads.thread', verbose_name='Ip')),
            ],
            options={
                'verbose_name': 'Ip harakati',
                'verbose_name_plural': 'Ip harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
