# Generated by Django 5.0.6 on 2026-05-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSupplierDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor (kg)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qarz summasi')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="To'langan")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('credit', 'Qarz')], default='credit', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'liq to'langan")),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread', verbose_name='Ip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov summasi")),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='threads.threadsupplierdebt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
