# Generated by Django 5.0.6 on 2026-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_threadsupplierdebt_supplierpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadsupplierdebt',
            name='payment_type',
            field=models.CharField(default='credit', max_length=20),
        ),
    ]
